//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios_Curso.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class CURSo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CURSo()
        {
            this.DETAlleFACTuras = new HashSet<DETAlleFACTura>();
            this.DETAlleINSCripcions = new HashSet<DETAlleINSCripcion>();
        }
    
        public int Codigo { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Duracion { get; set; }
        public string Nivel { get; set; }
        public Nullable<int> CodigoAsignatura { get; set; }
        public Nullable<int> CodigoHorario { get; set; }
        public string DocumentoProfesor { get; set; }
        public string DocumentoEstudiante { get; set; }
        public Nullable<int> CodigoAsistencia { get; set; }
        public Nullable<int> CodigoEvaluacion { get; set; }
        public Nullable<int> CodigoCalificacion { get; set; }
        [JsonIgnore]
        public virtual ASIGnatura ASIGnatura { get; set; }
        [JsonIgnore]
        public virtual ASIStencia ASIStencia { get; set; }
        [JsonIgnore]
        public virtual CALIficacion CALIficacion { get; set; }
        [JsonIgnore]
        public virtual EVALuacion EVALuacion { get; set; }
        [JsonIgnore]
        public virtual HORArio HORArio { get; set; }
        [JsonIgnore]
        public virtual PROFesor PROFesor { get; set; }
        [JsonIgnore]
        public virtual ESTUdiante ESTUdiante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<DETAlleFACTura> DETAlleFACTuras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<DETAlleINSCripcion> DETAlleINSCripcions { get; set; }
    }
}
