//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios_Curso.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBCursoEntities : DbContext
    {
        public DBCursoEntities()
            : base("name=DBCursoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ASIGnatura> ASIGnaturas { get; set; }
        public virtual DbSet<ASIStencia> ASIStencias { get; set; }
        public virtual DbSet<CALIficacion> CALIficacions { get; set; }
        public virtual DbSet<CURSo> CURSoes { get; set; }
        public virtual DbSet<DETAlleFACTura> DETAlleFACTuras { get; set; }
        public virtual DbSet<DETAlleINSCripcion> DETAlleINSCripcions { get; set; }
        public virtual DbSet<ESTUdiante> ESTUdiantes { get; set; }
        public virtual DbSet<EVALuacion> EVALuacions { get; set; }
        public virtual DbSet<FACTura> FACTuras { get; set; }
        public virtual DbSet<HORArio> HORArios { get; set; }
        public virtual DbSet<INSCripcion> INSCripcions { get; set; }
        public virtual DbSet<MATErial> MATErials { get; set; }
        public virtual DbSet<PROFesor> PROFesors { get; set; }
        public virtual DbSet<SESIon> SESIons { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TEMA> TEMAs { get; set; }
    }
}
