//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios_Curso.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class DETAlleFACTura
    {
        public int Codigo { get; set; }
        public int NumeroFactura { get; set; }
        public int CodigoCurso { get; set; }
        public int ValorUnitario { get; set; }
        [JsonIgnore]
        public virtual CURSo CURSo { get; set; }
        [JsonIgnore]
        public virtual FACTura FACTura { get; set; }
    }
}
