//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios_Curso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSCripcion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INSCripcion()
        {
            this.DETAlleINSCripcions = new HashSet<DETAlleINSCripcion>();
        }
    
        public int Codigo { get; set; }
        public Nullable<System.DateTime> FechaInscripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETAlleINSCripcion> DETAlleINSCripcions { get; set; }
    }
}
