//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios_Curso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMA
    {
        public int Codigo { get; set; }
        public string NombreTema { get; set; }
        public string Descripcion { get; set; }
    }
}
